name: Build and Push Docker Image to JFrog

on:
  push:
    branches: [ main ]

env:
  APP_NAME: express-backend-app
  APP_VERSION: 1.0.0
  DOCKER_REPO: docker-dev-local
  ARTIFACTORY_DOCKER_HOST: triald331v3.jfrog.io

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Allow CLI to use env vars
        run: echo "Unblocking JF_URL and JF_ACCESS_TOKEN for CLI"
        env:
          JFROG_CLI_ENV_EXCLUDE: ""

      - name: Test connection to JFrog
        run: jf rt ping

      - name: Build Docker image
        run: |
          docker build -t $APP_NAME:$APP_VERSION .

      - name: Tag Docker image for Artifactory
        run: |
          docker tag $APP_NAME:$APP_VERSION $ARTIFACTORY_DOCKER_HOST/$DOCKER_REPO/$APP_NAME:$APP_VERSION

      - name: Push Docker image to Artifactory
        run: |
          docker push $ARTIFACTORY_DOCKER_HOST/$DOCKER_REPO/$APP_NAME:$APP_VERSION
