name: Build and Push Docker Image to JFrog

on:
  push:
    branches: [ main ]

env:
  APP_NAME: express-backend-app
  APP_VERSION: 1.0.0
  DOCKER_REPO: docker-dev-local
  ARTIFACTORY_URL: https://triald331v3.jfrog.io/

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Configure JFrog CLI
        run: |
          jf c add artifactory-server \
            --url $ARTIFACTORY_URL \
            --access-token ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Test connection
        run: jf rt ping
        env:
          JFROG_CLI_SERVER_ID: artifactory-server

      - name: Build Docker image
        run: |
          docker build -t $APP_NAME:$APP_VERSION .

      - name: Tag Docker image for Artifactory
        run: |
          docker tag $APP_NAME:$APP_VERSION $ARTIFACTORY_URL/$DOCKER_REPO/$APP_NAME:$APP_VERSION

      - name: Push Docker image to Artifactory
        run: |
          docker push $ARTIFACTORY_URL/$DOCKER_REPO/$APP_NAME:$APP_VERSION
